name: runner

on: push

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16
      
      - name: install dependencies
        run: npm install
        
      - name: exec
        run: node main.js
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_LOGIN: seanghay