name: runner

on: 
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *


jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16
      
      - name: install dependencies
        run: npm install
        
      - name: execute
        run: node main.js
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_LOGIN: ${{ github.repository_owner }}
      
      - name: generate docs
        run: node generator.js

      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: dataset update"
          file_pattern: "./data/**/*.json **/*.md"